import type { ReactNode } from "react";

/**
 * Typography rules for long-form prose. Wraps content in a column with
 * editorial type rhythm using the existing titanium tokens. Each h2 becomes a
 * navigable anchor (auto-generated by parent ToC by reading the rendered DOM
 * or by passing structured sections).
 */
export function ArticleBody({ children }: { children: ReactNode }) {
  return <div className="article-body">{children}</div>;
}

/**
 * Render a single article section with auto-generated anchor id.
 * Use this to compose article content from a structured array.
 */
export function ArticleSection({
  heading,
  id,
  children,
}: {
  heading: string;
  id: string;
  children: ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-32 pt-12 first:pt-0">
      <h2 className="mb-5 text-[clamp(1.4rem,3vw,1.9rem)]" style={{ color: "var(--fg)" }}>
        {heading}
      </h2>
      <div className="space-y-5 text-[1.02rem] leading-[1.75]" style={{ color: "var(--fg-soft)" }}>
        {children}
      </div>
    </section>
  );
}

/** Render an array-of-strings or pre-split paragraphs from a text block. */
export function ProseParagraphs({ text }: { text: string }) {
  const paragraphs = text.split(/\n\n+/).map((p) => p.trim()).filter(Boolean);
  return (
    <>
      {paragraphs.map((p, i) => (
        <p key={i}>{p}</p>
      ))}
    </>
  );
}

// Hoisted RegExps — created once at module load, not on every call.
const NON_ALPHANUM = /[^a-z0-9\s-]/g;
const WHITESPACE = /\s+/g;
const MULTI_DASH = /-+/g;
const EDGE_DASH = /^-|-$/g;

/** Convert a section heading to a slug usable as an id / ToC anchor. */
export function slugifyHeading(s: string): string {
  return s
    .toLowerCase()
    .replace(NON_ALPHANUM, "")
    .replace(WHITESPACE, "-")
    .replace(MULTI_DASH, "-")
    .replace(EDGE_DASH, "");
}
